---
- hosts: web
  tasks:
    - name: Install php
      yum:
        name: php
        state: present

- hosts: web
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present
